# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "Dain Saint"

author:
  # facebook:         your-id
  # youtubeUser:      your-id
  # youtubeChannel:   your-id
  twitter:          dainsaint
  # github:           your-id
  # stackoverflow:    your-id
  # quora:            your-id
  # linkedin:         your-id
  # pinterest:        your-id
  # googlePlus:       your-id
  instagram:        dainsaint
  # reddit:           your-id
  # medium:           your-id
  # tumblr:           your-id
  email:            dain@cipherprime.com

copyright:
  year:             2019
  name:             Dain Saint

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "dainsaint"

# URL
url:                "https://dainsaint.com" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           America/New_York
permalink:          /:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  # - name:           "Tags"
  #   url:            "/tags"
  # - name:           "Github"
  #   url:            "https://github.com/AWEEKJ/Kiko-plus"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]
